"""schema_iniziale

Revision ID: 8d11e162a991
Revises: 
Create Date: 2026-04-06 23:54:17.456544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8d11e162a991'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=True),
    sa.Column('dimensione', sa.String(length=50), nullable=True),
    sa.Column('sito', sa.String(length=300), nullable=True),
    sa.Column('profilo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='commerciale'
    )
    op.create_table('soggetti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('telefono', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('organizzazione_id', sa.Integer(), nullable=True),
    sa.Column('ruolo', sa.String(length=100), nullable=True),
    sa.Column('tag', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('profilo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('memoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruolo_agente', sa.String(length=30), nullable=False),
    sa.Column('chiave', sa.String(length=200), nullable=False),
    sa.Column('valore', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vettore', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='decisionale'
    )
    op.create_table('proposte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruolo_agente', sa.String(length=30), nullable=False),
    sa.Column('tipo_azione', sa.String(length=100), nullable=False),
    sa.Column('titolo', sa.String(length=300), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('destinatario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('livello_rischio', sa.String(length=10), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('approvato_da', sa.String(length=200), nullable=True),
    sa.Column('canale_approvazione', sa.String(length=20), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deciso_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eseguito_il', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='decisionale'
    )
    op.create_table('sessioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('partecipanti', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('consenso', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflitti', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='decisionale'
    )
    op.create_table('configurazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chiave', sa.String(length=200), nullable=False),
    sa.Column('valore', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chiave'),
    schema='sistema'
    )
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('origine', sa.String(length=100), nullable=False),
    sa.Column('dati', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema'
    )
    op.create_table('regole_rischio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_azione', sa.String(length=100), nullable=False),
    sa.Column('livello_rischio', sa.String(length=10), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('approvazione_automatica', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema'
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('ruolo', sa.String(length=20), nullable=False),
    sa.Column('perimetro', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_accesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='sistema'
    )
    op.create_table('fascicoli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soggetto_id', sa.Integer(), nullable=True),
    sa.Column('ente_id', sa.Integer(), nullable=True),
    sa.Column('sintesi', sa.Text(), nullable=True),
    sa.Column('indice_rischio', sa.Float(), nullable=True),
    sa.Column('indice_opportunita', sa.Float(), nullable=True),
    sa.Column('generato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sezioni', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['ente_id'], ['commerciale.enti.id'], ),
    sa.ForeignKeyConstraint(['soggetto_id'], ['core.soggetti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='commerciale'
    )
    op.create_table('opportunita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ente_id', sa.Integer(), nullable=True),
    sa.Column('soggetto_id', sa.Integer(), nullable=True),
    sa.Column('titolo', sa.String(length=300), nullable=False),
    sa.Column('fase', sa.String(length=30), nullable=False),
    sa.Column('valore_eur', sa.Float(), nullable=True),
    sa.Column('probabilita', sa.Float(), nullable=True),
    sa.Column('chiusura_prevista', sa.Date(), nullable=True),
    sa.Column('dettagli', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['ente_id'], ['commerciale.enti.id'], ),
    sa.ForeignKeyConstraint(['soggetto_id'], ['core.soggetti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='commerciale'
    )
    op.create_table('flussi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soggetto_id', sa.Integer(), nullable=False),
    sa.Column('canale', sa.String(length=20), nullable=False),
    sa.Column('direzione', sa.String(length=10), nullable=False),
    sa.Column('oggetto', sa.String(length=500), nullable=True),
    sa.Column('contenuto', sa.Text(), nullable=True),
    sa.Column('dati_grezzi', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vettore', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('ricevuto_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('elaborato_il', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['soggetto_id'], ['core.soggetti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('risorse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soggetto_id', sa.Integer(), nullable=True),
    sa.Column('origine', sa.String(length=20), nullable=False),
    sa.Column('titolo', sa.String(length=500), nullable=False),
    sa.Column('contenuto', sa.Text(), nullable=True),
    sa.Column('vettore', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadati', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soggetto_id'], ['core.soggetti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('permessi_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('azione', sa.String(length=50), nullable=False),
    sa.Column('concesso', sa.Boolean(), nullable=False),
    sa.Column('creato_da', sa.String(length=200), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['sistema.utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema'
    )
    op.create_table('interazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunita_id', sa.Integer(), nullable=True),
    sa.Column('soggetto_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('pianificato_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completato_il', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunita_id'], ['commerciale.opportunita.id'], ),
    sa.ForeignKeyConstraint(['soggetto_id'], ['core.soggetti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='commerciale'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interazioni', schema='commerciale')
    op.drop_table('permessi_custom', schema='sistema')
    op.drop_table('risorse', schema='core')
    op.drop_table('flussi', schema='core')
    op.drop_table('opportunita', schema='commerciale')
    op.drop_table('fascicoli', schema='commerciale')
    op.drop_table('utenti', schema='sistema')
    op.drop_table('regole_rischio', schema='sistema')
    op.drop_table('registro', schema='sistema')
    op.drop_table('configurazione', schema='sistema')
    op.drop_table('sessioni', schema='decisionale')
    op.drop_table('proposte', schema='decisionale')
    op.drop_table('memoria', schema='decisionale')
    op.drop_table('soggetti', schema='core')
    op.drop_table('enti', schema='commerciale')
    # ### end Alembic commands ###
